#!/usr/bin/python3
__author__ = 'Kellan Childers'

import curses
from mainscreen import MainScreen
from util import center_start


def game(stdscr):
    # Ensures a clean visual space.
    stdscr.clear()
    curses.curs_set(False)

    # Sets the three main colors for the Conway graph.
    # First color: text. Second color: background.
    curses.init_pair(1, curses.COLOR_WHITE, curses.COLOR_BLUE)
    curses.init_pair(2, curses.COLOR_BLACK, curses.COLOR_WHITE)
    curses.init_pair(3, curses.COLOR_BLACK, curses.COLOR_BLACK)
    stdscr.bkgd(' ', curses.color_pair(2))

    console_height, console_width = stdscr.getmaxyx()
    _, title_x = center_start(console_height, console_width, 1, 26)
    stdscr.addstr(0, title_x, "RecAppE by Kellan Childers", curses.A_BOLD | curses.A_UNDERLINE)

    stdscr.refresh()

    main_screen = MainScreen(console_height, console_width)
    main_screen.show_intro()
    main_screen.start_command()

    stdscr.getkey()

if __name__ == "__main__":
    # curses.wrapper ensures that program will always fully exit from curses mode if an error occurs.
    curses.wrapper(game)
